version: "3.8"

services:
  backend-3:
    build:
      context: ./backend
    container_name: backend-3
    ports:
      - "3001:3000" # Backend için dış port 3000
    environment:
      - MONGO_URI=mongodb://mongo:27017/FAS
    depends_on:
      - mongo
    restart: always

  frontend-3:
    build:
      context: ./frontend
    container_name: frontend-3
    depends_on:
      - backend-3
    ports:
      - "5173:80" # Frontend için dış port 5173
    restart: always

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
